name: todo_admin
description: Admin panel to manage to-do list for specific users
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: ">=2.7.0 <3.1.0"

dependencies:
  flutter:
    sdk: flutter
  anxeb_flutter:
    path: ../anxeb-flutter # using a relative path for CI convenience
  control_style: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.1

flutter_icons:
  web:
    generate: true
    image_path: "assets/icons/web.png"

flutter:
  uses-material-design: true
  assets:
    - assets/i18n/
    - assets/icons/
    - assets/images/brand/
    - assets/images/social/
    - assets/images/common/
